version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

commands:
  cmd_write_manifest:
    description: "Create a manifest file"
    parameters:
      manifestFile:
        type: string
        default: "./manifest.txt"
      versionFile:
        type: string
    steps:
      - run: 'echo "Repository: << pipeline.project.git_url >>"  > << parameters.manifestFile >>'
      - run: 'echo "Branchname: << pipeline.git.branch >>" >> << parameters.manifestFile >>'
      - run: 'echo "Commit SHA: << pipeline.git.revision >> " >> << parameters.manifestFile >>'
      - run: 'echo "CircleCI Build-URL: $CIRCLE_BUILD_URL" >> << parameters.manifestFile >>'
      - run: 'echo "Pull request: $CIRCLE_PULL_REQUEST" >> << parameters.manifestFile >>'
      - run: 'echo -n "Version: " | cat - << parameters.versionFile >> >> << parameters.manifestFile >>'

jobs:
  build:
    docker:
      - image: rikorose/gcc-cmake
    steps:
      - checkout
      - run: cmake -S . -B build
      - run: cmake --build build --config Release --parallel 2
      - cmd_write_manifest:
          manifestFile: ./manifest.txt
          versionFile: ./version.txt
      - run: tar -zcvf pipeline-<< pipeline.number >>-<< pipeline.git.revision >>.tar.gz ./build/test* ./manifest.txt
      - store_artifacts:
          path: ./pipeline-<< pipeline.number >>-<< pipeline.git.revision >>.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - ./pipeline-<< pipeline.number >>-<< pipeline.git.revision >>.tar.gz
  
  deploy:
    docker:
      - image: linux-amd64
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/copy:
          from: /tmp/workspace/pipeline-<< pipeline.number >>-<< pipeline.git.revision >>.tar.gz
          to: 's3://c360-ci-artifacts'

workflows:
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
