version: 2.1

jobs:
  build:
    docker:
      - image: mhart/alpine-node
    steps:
      - checkout
      - run: 'echo "Repo: << pipeline.project.git_url >>"  > ./manifest.txt'
      - run: 'echo "Branchname: << pipeline.git.branch >>" >> ./manifest.txt'
      - run: 'echo "SHA: << pipeline.git.revision >> " >> ./manifest.txt'
      - run: 'echo "Build: $CIRCLE_BUILD_URL" >> ./manifest.txt'  
      - store_artifacts:
          path: ./manifest.txt

workflows:
  build:
    jobs:
      - build
