version: 2.1

commands:
  cmd_write_manifest:
    description: "Create a manifest file"
    parameters:
      filename:
        type: string
        default: "./manifest.txt"
    steps:
      - run: 'echo "Repository: << pipeline.project.git_url >>"  > << parameters.filename >>'
      - run: 'echo "Branchname: << pipeline.git.branch >>" >> << parameters.filename >>'
      - run: 'echo "Commit SHA: << pipeline.git.revision >> " >> << parameters.filename >>'
      - run: 'echo "CircleCI Build-URL: $CIRCLE_BUILD_URL" >> << parameters.filename >>'
      - run: 'echo "PR: $CIRCLE_PULL_REQUEST" >> << parameters.filename >>'

jobs:
  build:
    docker:
      - image: mhart/alpine-node
    steps:
      - checkout
      - cmd_write_manifest:
          filename: ./manifest.txt
      - store_artifacts:
          path: ./manifest.txt

workflows:
  build:
    jobs:
      - build
